server:
  port: 8090


spring:
    application:
        name: auth
    datasource:
        dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        url: jdbc:mysql://${DB_URL:localhost}:${DB_PORT:3306}/${DB_NAME:shiro}
        databaseName:
        serverName:
        username: ${DB_USERNAME:root}
        password: ${DB_PASSWORD:}
    jpa:
        database-platform: org.hibernate.dialect.MySQLInnoDBDialect
        database: MYSQL
        openInView: false
        show_sql: true
        generate-ddl: true
        hibernate:
            ddl-auto: validate
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false

            
